export enum CustomExceptionCode {
  INVALID_USER = 'INVALID_USER',

  INVALID_JWT = 'INVALID_JWT',
  EXPIRED_JWT = 'EXPIRED_JWT',

  INVALID_WORD = 'INVALID_WORD',
  NOTFOUND_WORD = 'NOTFOUND_WORD',

  INVALID_QUIZ = 'INVALID_QUIZ',
  FINISHED_QUIZ = 'FINISHED_QUIZ',
}
