export enum CustomExceptionCode {
  // AUTH/USER 10000
  INVALID_USER = 'INVALID_USER',

  // JWT 20000
  INVALID_JWT = 'INVALID_JWT',
  EXPIRED_JWT = 'EXPIRED_JWT',

  // WORD 30000
  INVALID_WORD = 'INVALID_WORD',
  NOTFOUND_WORD = 'NOTFOUND_WORD',
}
